name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
    branches: [main]
  push:
    branches:
      - main
      - "releases/*"
      - kerry

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all

      - name: Set Maven Version
        run: |
          echo "maven-version=3.8.5" >> $GITHUB_ENV

      - name: Download Maven
        uses: ./
        with:
          maven-version: ${{ env.maven-version }}

      - name: Test Maven
        run: __tests__/verify-maven.sh ${{ env.maven-version }}
        shell: bash

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Maven Version
        run: |
          echo "maven-version=3.8.5" >> $GITHUB_ENV

      - name: Download Maven
        uses: ./
        with:
          maven-version: ${{ env.maven-version }}

      - name: Test Maven
        run: __tests__/verify-maven.sh ${{ env.maven-version }}
        shell: bash
