name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - "releases/*"
      - kerry

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
      - uses: ./
        with:
          maven-version: "3.8.2"
      - name: test maven
        run: __tests__/verify-maven.sh ${{ maven-version }}
        shell: bash

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          maven-version: "3.8.2"
      - name: test maven
        run: __tests__/verify-maven.sh ${{ maven-version }}
        shell: bash
